import Foundation

enum Kind: String {
  case sync = "Sync"
  case async = "Async"

  var protocolName: String { "\(rawValue)Migration" }
  var migrateBody: String {
    switch self {
    case .sync: return "func migrate() throws {}"
    case .async: return "func migrate() async throws {}"
    }
  }
}

func emitChain(_ n: Int, _ kind: Kind) -> [String] {
  let prefix = "Chain\(n)\(kind.rawValue)Node"
  var lines = [
    "struct \(prefix)0: \(kind.protocolName) { static let id = MigrationID(\"\(prefix)0\"); \(kind.migrateBody) }"
  ]
  for i in 1..<n {
    let prev = i - 1
    lines.append(
      "struct \(prefix)\(i): \(kind.protocolName) { static let id = MigrationID(\"\(prefix)\(i)\"); static let dependencies: [any \(kind.protocolName).Type] = [\(prefix)\(prev).self]; \(kind.migrateBody) }"
    )
  }
  return lines
}

func emitFanout(_ n: Int) -> [String] {
  let prefix = "Fanout\(n)Node"
  return (0..<n).map { i in
    "struct \(prefix)\(i): SyncMigration, AsyncMigration { static let id = MigrationID(\"\(prefix)\(i)\"); func migrate() throws {}; func migrate() async throws {} }"
  }
}

func emitFanin(_ n: Int, _ kind: Kind) -> [String] {
  let prefix = "Fanin\(n)\(kind.rawValue)Node"
  var lines = (0..<(n - 1)).map { i in
    "struct \(prefix)\(i): \(kind.protocolName) { static let id = MigrationID(\"\(prefix)\(i)\"); \(kind.migrateBody) }"
  }
  let deps = (0..<(n - 1)).map { "\(prefix)\($0).self" }.joined(separator: ", ")
  lines.append(
    "struct \(prefix)Root: \(kind.protocolName) { static let id = MigrationID(\"\(prefix)Root\"); static let dependencies: [any \(kind.protocolName).Type] = [\(deps)]; \(kind.migrateBody) }"
  )
  return lines
}

func emitTree(_ n: Int, _ kind: Kind) -> [String] {
  let prefix = "Tree\(n)\(kind.rawValue)Node"
  var lines = [
    "struct \(prefix)0: \(kind.protocolName) { static let id = MigrationID(\"\(prefix)0\"); \(kind.migrateBody) }"
  ]
  for i in 1..<n {
    let parent = (i - 1) / 2
    lines.append(
      "struct \(prefix)\(i): \(kind.protocolName) { static let id = MigrationID(\"\(prefix)\(i)\"); static let dependencies: [any \(kind.protocolName).Type] = [\(prefix)\(parent).self]; \(kind.migrateBody) }"
    )
  }
  return lines
}

func emitArray(_ kind: Kind, varName: String, prefix: String, n: Int, extraName: String? = nil)
  -> String
{
  var elements = (0..<n).map { "\(prefix)\($0)()" }
  if let extraName {
    elements.append("\(prefix)\(extraName)()")
  }
  return
    "let \(varName)\(kind.rawValue): [any \(kind.protocolName)] = [\(elements.joined(separator: ", "))]"
}

func generateFixtures() -> String {
  var output = "// Generated by FixtureGeneratorTool — do not edit by hand.\nimport Migrations\n\n"

  for n in [10, 100, 1000] {
    output += emitChain(n, .sync).joined(separator: "\n") + "\n"
    output += emitChain(n, .async).joined(separator: "\n") + "\n"
    output += emitFanout(n).joined(separator: "\n") + "\n"
    output += emitFanin(n, .sync).joined(separator: "\n") + "\n"
    output += emitFanin(n, .async).joined(separator: "\n") + "\n"
    output += emitTree(n, .sync).joined(separator: "\n") + "\n"
    output += emitTree(n, .async).joined(separator: "\n") + "\n"
    output += "\n"
    output += emitArray(.sync, varName: "chain\(n)", prefix: "Chain\(n)SyncNode", n: n) + "\n"
    output += emitArray(.async, varName: "chain\(n)", prefix: "Chain\(n)AsyncNode", n: n) + "\n"
    output += emitArray(.sync, varName: "fanout\(n)", prefix: "Fanout\(n)Node", n: n) + "\n"
    output += emitArray(.async, varName: "fanout\(n)", prefix: "Fanout\(n)Node", n: n) + "\n"
    output +=
      emitArray(
        .sync, varName: "fanin\(n)", prefix: "Fanin\(n)SyncNode", n: n - 1, extraName: "Root")
      + "\n"
    output +=
      emitArray(
        .async, varName: "fanin\(n)", prefix: "Fanin\(n)AsyncNode", n: n - 1, extraName: "Root")
      + "\n"
    output += emitArray(.sync, varName: "tree\(n)", prefix: "Tree\(n)SyncNode", n: n) + "\n"
    output += emitArray(.async, varName: "tree\(n)", prefix: "Tree\(n)AsyncNode", n: n) + "\n"
    output += "\n"
  }

  return output
}

guard CommandLine.arguments.count > 1 else {
  fatalError("Usage: FixtureGeneratorTool <output-directory>")
}

let outputDirectory = URL(fileURLWithPath: CommandLine.arguments[1])
try FileManager.default.createDirectory(at: outputDirectory, withIntermediateDirectories: true)
let outputFile = outputDirectory.appendingPathComponent("GeneratedFixtures.swift")
try generateFixtures().write(to: outputFile, atomically: true, encoding: .utf8)
